### Em vez de organizar uma tabela bonitinha no Excel/Spreadsheets, eu decidi criar uma tabela e visualizá-la utilizando o Pandas.

A atividade pede para que eu e os meus colegas coletemos informações sobre:

1. O tempo que cada um leva pra chegar à escola
2. O tempo que cada um passa nas aulas
3. O tempo que cada um passa nos intervalos
4. O tempo que cada um leva no deslocamento de volta para casa

Devemos usar esses dados para entender como as aulas e os intervalos podem ser melhores distribuídos para tornar o horário escolar mais equilibrado para todos.

Como a oficina tem um caráter originalmente coletivo mas a atividade atribuída é de caráter individual, algumas alterações pontuais serão feitas:

1. Apenas o meu tempo vai ser levado em consideração e
2. Se eu conseguir, alguns colegas de curso vão me fornecer os dados deles, de forma que eu possa montar uma tabelinha mais completa. :)

Depois de preparar esses dados, eu farei uma breve análise considerando o tempo que eu gasto em cada atividade ao longo do dia. O ponto final da oficina sugeria uma "discussão com os colegas para melhorar o cronograma da escola" mas, como no meu caso é ensino superior público, eu acredito que não haja muito espaço pra discussão de cronogramas, não. :P

Mãos à obra!

In [6]:
# primeiro, a gente baixa cos pip - aqui, a gente vai trabalhar com pandas (pra organizar os números) e o numpy (pra deixar os números belos)

!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /home/elexei/.pyenv/versions/3.10.11/lib/python3.10/site-packages (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/elexei/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/elexei/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from pandas) (2024.2)
Requirement already satisfied: numpy>=1.22.4 in /home/elexei/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from pandas) (2.1.2)
Requirement already satisfied: tzdata>=2022.7 in /home/elexei/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /home/elexei/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: numpy in /home/elexei/.pyenv/versions/3.10.11/lib/python3.10/site-packages (2.1.2)

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: matplotlib in /home/elexei/.pyenv/versions/3.10.11/lib/python3.10/site-packages (3.9.2)
Requirement already satisfied: fonttools>=4.22.0 in /home/elexei/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from matplotlib) (4.54.1)
Requirement already satisfied: pyparsing>=2.3.1 in /home/elexei/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: numpy>=1.23 in /home/elexei/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from matplotlib) (2.1.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/elexei/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: cycler>=0.10 in /home/elexei/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: python-dateutil>=2.7 in /home/elexei/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: packaging>=20.0 in /home/elexei/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from matplotlib) (24.1)
Requirement already satisfied: contourpy>=1.0.1 in /home/elexei/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: pillow>=8 in /home/elexei/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from matplotlib) (11.0.0)
Requirement already satisfied: six>=1.5 in /home/elexei/.pyenv/versions/3.10.11/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip

In [38]:
# e agora a gente importa os negócio

import pandas as pd
import numpy as np

In [39]:
# começar populando, manualmente, um dicionário python composto por pessoas, seus dias na semana, momentos do dia e o tempo aplicado neles
weekday_activities = {
    # De quem estamos falando?
    'Rafael' : {
        # De qual dia da semana?
        'Segunda' : {
            # De qual parte do dia? Quanto tempo, em minutos, leva em média?
            'Ida' : 60,
            'Aula' : 40 * 4,
            'Intervalo' : 20,
            'Volta' : 90,
        },
        'Terça' : {
            # De qual parte do dia? Quanto tempo, em minutos, leva em média?
            'Ida' : 60,
            'Aula' : 40 * 2,
            'Intervalo' : 20,
            'Volta' : 60,
        },
        'Quarta' : {
            # De qual parte do dia? Quanto tempo, em minutos, leva em média?
            'Ida' : 60,
            'Aula' : 40 * 2,
            'Intervalo' : 20,
            'Volta' : 90,
        },
        'Quinta' : {
            # De qual parte do dia? Quanto tempo, em minutos, leva em média?
            'Ida' : 60,
            'Aula' : 40 * 4,
            'Intervalo' : 20,
            'Volta' : 90,
        },
        'Sexta' : {
            # De qual parte do dia? Quanto tempo, em minutos, leva em média?
            'Ida' : 60,
            'Aula' : 40 * 1,
            'Intervalo' : 20,
            'Volta' : 60,
        },
    },
}

In [40]:
# Primeiro de tudo, vamo criar um DataFrame pandas e atribuí-lo a uma variável? fica melhor de manipular assim.
df = pd.DataFrame(weekday_activities['Rafael'])

df

           Segunda  Terça  Quarta  Quinta  Sexta
Ida             60     60      60      60     60
Aula           160     80      80     160     40
Intervalo       20     20      20      20     20
Volta           90     60      90      90     60

In [56]:
# Bom, aparentemente a tabelinha tá funcionando, mas tá fei (rorosa)! E se eu quiser ajustar essa tabelinha pra mudar de tamanho e separar as informações de forma melhor?

df.style.background_gradient(cmap = 'BuPu') \
        .set_caption('Programação diária de Rafael')

In [59]:
# Certo. A gente colocou umas corzinhas e adicionou um título. Mas e se todo dataframe que eu fizer eu quiser aplicar esses estilos?

def stylize(styler):
    styler.background_gradient(cmap = 'PuBu') # --- mudei de cor pra provar que funcionou
    styler.set_caption('Programação diária de Rafael (em minutos)')

    return styler

df.style.pipe(stylize)

Pronto. Agora temos todos os dias da semana do meu dia-a-dia - só os dias úteis, claro; no fim de semana, estudo de casa mesmo. Tudo isso numa tabelinha colorida e intitulada.